# Download Dataset

In [1]:
import gdown
import os

class DriveContent:
  def __init__(self, file_name, url, target_dir="./data"):
    self.target_dir = target_dir
    self.file_path = os.path.join(target_dir, file_name)
    self.url = url
    self.download_file()

  def download_file(self):
    os.makedirs(self.target_dir, exist_ok=True)
    gdown.download(url=self.url, output=self.file_path, quiet=False)

In [2]:
posts = DriveContent(
    file_name='posts.csv',
    url='https://drive.google.com/file/d/1SL-r71hqfC1SHO03ZcyWPRGx5w_FaMql/view?usp=sharing'
  )

comments = DriveContent(
    file_name='comments.csv',
    url='https://drive.google.com/file/d/1Sm1xALXxS2IMK9K0I17hkebILHRBmVwG/view?usp=sharing'
  )

Downloading...
From: https://drive.google.com/uc?id=1SL-r71hqfC1SHO03ZcyWPRGx5w_FaMql
To: /home/nwxxb/Documents/sampling_differences_experiment/data/posts.csv
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8.01M/8.01M [00:00<00:00, 8.76MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Sm1xALXxS2IMK9K0I17hkebILHRBmVwG
To: /home/nwxxb/Documents/sampling_differences_experiment/data/comments.csv
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16.6M/16.6M [00:02<00:00, 5.78MB/s]

# preprocessing (before splitting)

In [3]:
import pandas as pd
pd.set_option('max_colwidth', 400)
pd.describe_option('max_colwidth')
pd.set_option('display.max_colwidth', None)

display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 400]

## convert to pandas

### Posts

In [4]:
# posts
dfposts = pd.read_csv(posts.file_path, index_col=0)

In [5]:
dfposts.head(5)

   post_id  \
0   1125.0
1  28834.0
2   6152.0
3    120.0
4    198.0

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 content  \

In [6]:
print(pd.unique(dfposts['topic_name']))
print(len(pd.unique(dfposts['topic_name'])))

['Kesehatan' 'Filsafat' 'Psikologi' 'Agama' 'Sains' 'Islam'
 'Ekonomi Bisnis' 'Politik' 'Pendidikan' 'Sosial Budaya' 'Sejarah'
 'Pertanian']
12

In [7]:
list(zip(pd.unique(dfposts['topic_id']), pd.unique(dfposts['topic_name'])))

[(51.0, 'Kesehatan'),
 (11.0, 'Filsafat'),
 (15.0, 'Psikologi'),
 (21.0, 'Agama'),
 (6.0, 'Sains'),
 (43.0, 'Islam'),
 (10.0, 'Ekonomi Bisnis'),
 (14.0, 'Politik'),
 (22.0, 'Pendidikan'),
 (13.0, 'Sosial Budaya'),
 (31.0, 'Sejarah'),
 (7.0, 'Pertanian')]

In [8]:
dfposts.shape

(15642, 4)

### Comments

In [9]:
# comments
dfcomments = pd.read_csv(comments.file_path, index_col=0)
dfcomments.tail(20)

,comment_id,content,post_id,topic_id,topic_name
67648,484909.0,Maka paling aman adalah membandingkan diri dengan diri kita sebelumnya dalam rangka evaluasi.,70699.0,43.0,Islam
67649,485000.0,"Seharusnya sih gak pengaruh, tapi bagi beberapa oknum yg menjadikan itu sebuah masalah.",70702.0,22.0,Pendidikan
67650,484895.0,"Pengaruh itu harus ada 2 variabel nim, anim hanya menyebutkan satu variabel, mungkin bisa lebih spesifik lagi, pengaruh apa? Terhadap apa?.... Anim hanya menyebutkan pengaruh pendapatan saja, bisa dilengkapi mungkin, pengaruh pendapatan terhadap apa...",70702.0,22.0,Pendidikan
67651,484891.0,"Mungkin kita bisa melihat pengaruh dari segi rasa keikhlasan, pengajar formal cenderung mengajar karena profesi, sedang ustadz mengajar karena bermanfaat. Meskipun itu tidak bisa menjadi tolak ukur. Disini keikhlasan yang menjadi tolak ukur pengaruhnya , orang yang mengajar didasarkan pada rasa keikhlasan akan membawakan materi yang dibutuhkan menjadi lebih murni, dalam artian mengesampingkan nafsu saat mengajar, jadi bisa membawakan materi dengan menyenangkan dan dapat menyentuh hati yang diajarkan. - Mungkin itu dari saya",70702.0,22.0,Pendidikan
67652,485005.0,Sebatas yang saya ketahui kurikulum pendidikan Indonesia tidak menyediakan tempat untuk siswa belajar membaca dan menulis namun dipersyaratkan harus bisa baca tulis. Mungkin saya salah.,70703.0,22.0,Pendidikan
67653,484907.0,"Membaca dan menulis juga bukan hal yg mudah, dari kisah nyata sehari hariku ketika ngajari adek yg masih tk untuk membaca dan menulis itu sangat susah, generasi sekarang itu beda dengan generasi dulu. Hemat saya, membaca dan menulis itu kok harus dilakukan oleh orangtua, gak harus dimasukkan dalam kurikulum sekolah formal. Aku berpikir bahwa pentingnya parenting, peran orang tua buat ikut andil dalam mendidik anaknya. Kurasa dari hal diatas itu secara gak langsung nyuruh orang tua (pendidikan informal, nonformal, buat ikut andil dalam tanggungjawab pendidikan nasional). Semua ada +/- memang, positifnya bahwa dengan adanya pendidikan parenting/lingkungan sekitar yg harus membantu anak dalam proses belajar mengajar, secara gak langsung akan merubah pola pikir bahwa **belajar itu gak harus di sekolah.**",70703.0,22.0,Pendidikan
67654,484961.0,"Menurut pemikiran saya, membaca dan menulis bisa dilakukan secara pararel (dirumah & disekolah). agar ada kesinambungan dan kontrol yang baik dari pihak sekolah ataupun dr pihak orang tua. Kurang baik apabila kurikulum menulis dan membaca dihilangkan, terkesan siswa sebelum masuk ke TK atau SD harus sudah bisa membaca dan menulis.",70703.0,22.0,Pendidikan
67655,484921.0,"rumusan kurikulum saya juga kurang begitu paham ... saya rasa pemerintah konsep nya masih meniru negara"" luar jadi bila di terapkan di indonesia sendiri kurang relefan... seharusnya riset dan membuat kurikulum sendiri yg lebih efektif...",70703.0,22.0,Pendidikan
67656,484918.0,"Kiblat pendidikan indonesia masih ke Finlandia dan negara2 maju semacamnya nim. Baca tulis itu secara pertumbuhan jiwa dan neurosains akan memotong masa bermain/bersenang2 anak golden age. Di amerika aja udah ada negara2 bagian yg berangkat sekolahnya menyesuaikan bangun tidur anak. Jd ga ada kata kesiangan/telat masuk, karena sekolah memberi kebebasan buat anak2 yg bangun kesiangan. Di indonesia, kita justru bangga anak2 balita bisa baca tulis. Pdhl secara pertumbuhan jiwa dan otak itu anomali dan sangat mungkin menabung efek depresi dlm kejiwaan anak. Setahu sayah nim.",70703.0,22.0,Pendidikan
67657,485049.0,Meneng,70710.0,11.0,Filsafat
67658,485010.0,kebijaksanaan,70710.0,11.0,Filsafat
67659,485003.0,"Filsafat untuk mencari hakikat kehidupan, dari mana, mau kemana, dan untuk apa dengan cara apa manusia seharusnya menjalani kehidupan.",70710.0,11.0,Filsafat
67660,484999.0,"Mungkin laku, tandang, atau aktualisasi.",70710.0,11.0,Filsafat
67661,484977.0,"Filsafat ada dari ketidaktahuan, maka puncak dari filsafat juga adalah ketidaktahuan dan kehampaan. karena dari ketidaktahuan muncul pengetahuan akan segala sesuatu secara konkret, nyata, dan lengkap nilainya. Dari yang sudah ada, manusia hanya menambah dan menimbun dengan pendapat dan argumen baru dengan hanya pengubahan bahasa sebagai pedoman dan pegangan untuk menemukan ide berbeda berdasarkan yang telah ada. hanya seperti, perubahan bentuk dari yang sudah ada di masa lalu.\n\nSemoga membantu🙏🙂",70710.0,11.0,Filsafat
67662,484982.0,"isi adalah kosong , kosong adalah isi",70710.0,11.0,Filsafat
67663,484975.0,"Ketidaktahuan nim, seperti ilmu yang lainnya dan ketidaktahuan mengantarkan kebijaksanaan, karena tau kalo sebenernya yang diketahui sedikit",70710.0,11.0,Filsafat
67664,484974.0,Apakah diatasnya puncak masih ada hal lain?,70710.0,11.0,Filsafat
67665,484972.0,Wisdom and Virtue who lead to happiness.,70710.0,11.0,Filsafat
67666,484978.0,Maksudnya merekayasa fisik manusia atau perilaku manusia? \n\nKalo fisik manusia ada ilmu Genetic Engineering\nKalo perilaku ada Social Engineering,70712.0,6.0,Sains
67667,484990.0,Ilegal kagak niih,70713.0,22.0,Pendidikan

In [10]:
print(pd.unique(dfcomments['topic_name']))
print(len(pd.unique(dfcomments['topic_name'])))

['Pertanian' 'Sejarah' 'Sosial Budaya' 'Sains' 'Pendidikan' 'Psikologi'
 'Politik' 'Ekonomi Bisnis' 'Islam' 'Agama' 'Filsafat' 'Kesehatan']
12

In [11]:
list(zip(pd.unique(dfcomments['topic_id']), pd.unique(dfcomments['topic_name'])))

[(7.0, 'Pertanian'),
 (31.0, 'Sejarah'),
 (13.0, 'Sosial Budaya'),
 (6.0, 'Sains'),
 (22.0, 'Pendidikan'),
 (15.0, 'Psikologi'),
 (14.0, 'Politik'),
 (10.0, 'Ekonomi Bisnis'),
 (43.0, 'Islam'),
 (21.0, 'Agama'),
 (11.0, 'Filsafat'),
 (51.0, 'Kesehatan')]

In [12]:
dfcomments.shape

(67668, 5)

## ONLY POST
if you only use post please run this and continue to "Drop nan rows"

In [13]:
df = dfposts

In [14]:
topics = pd.DataFrame({'topic_id': pd.unique(df['topic_id']), 'topic_name': pd.unique(df['topic_name'])})
topics.set_index('topic_id', inplace=True)

In [15]:
df.to_csv("./data/selected_dataset.csv", index=True, index_label="orig_index", encoding="utf-8")

In [16]:
df = df.drop(['post_id', 'topic_name'], axis=1)

## POST + COMMENTS

In [17]:
# df = pd.concat([dfposts, dfcomments], ignore_index=True)

In [18]:
# topics = pd.DataFrame({'topic_id': pd.unique(df['topic_id']), 'topic_name': pd.unique(df['topic_name'])})
# topics.set_index('topic_id', inplace=True)

In [19]:
# df.to_csv("./data/selected_dataset.csv", index=True, index_label="orig_index", encoding="utf-8")

In [20]:
# df = df.drop(['post_id', 'comment_id', 'topic_name'], axis=1)

## drop nan rows

In [21]:
print(df.info())
print(df.shape)
print([f"empty_{column}: {df[column].isnull().sum()}" for column in ['content', 'topic_id']])

<class 'pandas.core.frame.DataFrame'>
Index: 15642 entries, 0 to 15641
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   content   15642 non-null  object
 1   topic_id  15642 non-null  float64
dtypes: float64(1), object(1)
memory usage: 366.6+ KB
None
(15642, 2)
['empty_content: 0', 'empty_topic_id: 0']

In [22]:
df.loc[pd.isna(df["content"]), :]

Empty DataFrame
Columns: [content, topic_id]
Index: []

In [23]:
df_cleaned = df.dropna(subset=['content', 'topic_id'])
print(df_cleaned.info())
print(df_cleaned.shape)
print([f"empty_{column}: {df_cleaned[column].isnull().sum()}" for column in ['content', 'topic_id']])

<class 'pandas.core.frame.DataFrame'>
Index: 15642 entries, 0 to 15641
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   content   15642 non-null  object
 1   topic_id  15642 non-null  float64
dtypes: float64(1), object(1)
memory usage: 366.6+ KB
None
(15642, 2)
['empty_content: 0', 'empty_topic_id: 0']

In [24]:
df_cleaned.shape

(15642, 2)

## data overview

In [25]:
topic_row_count = df_cleaned.groupby(['topic_id']).count()
pd.concat([topic_row_count, topics], axis=1, keys=["rows_count", "topic"]).droplevel(1, axis=1)

          rows_count           topic
topic_id
6.0              471           Sains
7.0             1159       Pertanian
10.0            1190  Ekonomi Bisnis
11.0            1805        Filsafat
13.0             805   Sosial Budaya
14.0            1158         Politik
15.0            2854       Psikologi
21.0            1265           Agama
22.0            1002      Pendidikan
31.0             616         Sejarah
43.0            1827           Islam
51.0            1490       Kesehatan

In [26]:
topic_row_count['content'].sum()

15642

In [27]:
# Ilmu alam: Sains, Pertanian, Kesehatan, Psikologi
# Ilmu sosial: Ekonomi bisnis, Politik, Pendidikan, Sosial Budaya, Sejarah
# Lain-lain: Filsafat, agama, Islam
# display(topic_row_count)
display(topic_row_count.loc[[6.0, 7.0, 51.0, 15.0]])
ilmu_alam = topic_row_count.loc[[6.0, 7.0, 51.0, 15.0]].sum(axis=0)
ilmu_sosial = topic_row_count.loc[[10.0, 14.0, 22.0, 13.0, 31.0]].sum(axis=0)
lain_lain = topic_row_count.loc[[11.0, 21.0, 43.0]].sum(axis=0)
print(ilmu_alam, ilmu_sosial, lain_lain)

          content
topic_id
6.0           471
7.0          1159
51.0         1490
15.0         2854

content    5974
dtype: int64 content    4771
dtype: int64 content    4897
dtype: int64

# Random constant number

In [28]:
RANDOM_STATE = 11

# Divide train and test data (to prevent data leakage)

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
df_cleaned.columns

Index(['content', 'topic_id'], dtype='object')

In [31]:
X = df_cleaned['content']
y = df_cleaned['topic_id']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE)

In [32]:
df_cleaned.shape, X.shape, y.shape

((15642, 2), (15642,), (15642,))

In [33]:
pd.DataFrame({"label": ["X", "y"],
              "test": [X_test.size, y_test.size],
              "train": [X_train.size, y_train.size],
              "sum": [X_test.size + X_train.size, y_test.size + y_train.size],
              "actual_size": [X.size, y.size]
             })

  label  test  train    sum  actual_size
0     X  3129  12513  15642        15642
1     y  3129  12513  15642        15642

In [34]:
pd.concat(
    [y_train.value_counts().sort_index(),
     y_test.value_counts().sort_index()],
    axis=1,
    keys=["train", "test"],
)

          train  test
topic_id
6.0         377    94
7.0         927   232
10.0        952   238
11.0       1444   361
13.0        644   161
14.0        926   232
15.0       2283   571
21.0       1012   253
22.0        802   200
31.0        493   123
43.0       1461   366
51.0       1192   298

In [35]:
os.makedirs("./data", exist_ok=True)

train_df = pd.DataFrame({"content": X_train, "topic_id": y_train})
test_df  = pd.DataFrame({"content": X_test,  "topic_id": y_test})

train_df.to_csv("./data/train.csv", index=True, index_label="orig_index", encoding="utf-8")
test_df.to_csv("./data/test.csv",  index=True, index_label="orig_index", encoding="utf-8")

# Creating Pipelines and helper and other utilities

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, FunctionTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from imblearn.over_sampling  import RandomOverSampler
from imblearn.under_sampling  import RandomUnderSampler
import nltk
nltk_dir = os.path.abspath("./nltk_data")
os.makedirs(nltk_dir, exist_ok=True)
nltk.download("stopwords", download_dir=nltk_dir)
nltk.data.path.append(nltk_dir)
from nltk.tokenize import word_tokenize
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from nltk.corpus import stopwords
from mpstemmer import MPStemmer
from sklearn.base import BaseEstimator, TransformerMixin

## create helper/stateless transformer (will be converted to transformer using FunctionTransformer)

In [37]:
def normalize_unicode(X):
  # try to remove 𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺, ˢᵉᵐᵘᵃ, 𝐊𝐢𝐭𝐚, etc..
  X = X.copy()
  X = X.str.normalize('NFKC')
  return X

def remove_number(X):
  X = X.copy()
  X = X.str.replace(r"\d+", '')
  return X

def remove_feature_generated_mess(X):
  X = X.copy()
  X = X.str.replace(r"\[\[\^[(face|space)\-]{0,6}[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}\]\]", '')
  return X

def remove_underscore(X):
  X = X.copy()
  X = X.str.replace(r"_", ' ')
  return X

def remove_non_alphabetic(X):
  regex = r"[\u0600-\u06ff]|[\ua980-\ua9df]|[\u1b80-\u1bbf]|[\u1cc0-\u1ccf]|[\u1b00-\u1b7f]|[\u1bc0-\u1bff]|[\u4e00-\u9fff]|[\u0590-\u05ff]|[\ufb1d-\ufb4f]"
  X = X.copy()
  X = X.str.replace(regex, '')
  return X

def remove_kata_ulang(X):
  X = X.copy()
  X = X.str.replace(r"([a-z])(2)", r'\1', regex=True)
  return X

def remove_laughing(X): #TODO
  X = X.copy()
  X = X.str.replace(r"\b(?:[akiq]{0,2}[hwx]{1,2}[akiq]{0,2}){2,}h?\b", '', regex=True)
  return X

def test_print(X, payload):
  print(payload)
  return X

## loading stop words for tf_idf

In [38]:
# get stop words from Sastrawi
sastrawi_stop_words_factory = StopWordRemoverFactory()
indo_stop_words = sastrawi_stop_words_factory.get_stop_words()
# get english stop words from nltk
english_stop_words = stopwords.words('english')
# additional stop
additional_stop_words = [
    'dengan', 'ia', 'bahwa', 'oleh', 'http', 'https', 'com', 'org', 'www', 'html', 'lo', 'gw', 'loe', 'gue', 'yg',
    'kamu', 'tdk', 'elo', 'aku', 'daku', 'koe', 'apa', 'bagaimana', 'kapan', 'kpn', 'knp', 'apkh', 'siapa', 'merekalah',
    'dgn', 'msh', 'jg', 'lg', 'lgi', 'kok', 'sy', 'nim', 'nims', 'wah', 'tsb', 'bukan', 'bgt', 'banget', 'buanget', 'gimana', 'gmn',
    'anim', 'enggak', 'nih', 'ku', 'jadi', 'iy', 'gk', 'gak', 'ga', 'tapi', 'tp', 'iya', 'aja', 'aj', 'semua', 'kan',
    'rk', 'klo', 'kalo', 'utk', 'mu', 'sih', 'hai', 'ndak', 'si', 'yaelah', 'yakan', 'tidaklah', 'kalau', 'yo', 'tuh', 'yah',
    'yen', 'wis', 'wes', 'walaupun', 'wae', 'tsbt', 'yup', 'yak', 'waduh', 'woalah', 'yuk', 'tu', 'yes', 'wew', 'untk', 'ngga'
]

stop_words = indo_stop_words + english_stop_words + additional_stop_words

## Creating Pipeline

In [39]:
def show_params(pipe_obj):
  params = pipe_obj.get_params().copy()
  for k, v in params.items():
    if '__' in k:
      print(f"{k}: {v}")

In [40]:
from imblearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB

NB = Pipeline([
 ('normalize_unicode', FunctionTransformer(
     normalize_unicode
 )),
 ('remove_generated_mess', FunctionTransformer(
     remove_feature_generated_mess
 )),
 ('remove_underscore', FunctionTransformer(
     remove_underscore
 )),
 ('remove_number', FunctionTransformer(
     remove_number
 )),
 ('remove_non_alphabetic_char', FunctionTransformer(
     remove_non_alphabetic
 )),
 ('remove_kata_ulang', FunctionTransformer(
     remove_kata_ulang
 )),
 ('remove_laughing', FunctionTransformer(
     remove_laughing
 )),
 ('tf_idf', TfidfVectorizer(
     stop_words=stop_words
 )),
 ('algo', MultinomialNB())
])

# random over sampling
NB_imb_ROS = Pipeline([
 ('normalize_unicode', FunctionTransformer(
     normalize_unicode
 )),
 ('remove_generated_mess', FunctionTransformer(
     remove_feature_generated_mess
 )),
 ('remove_underscore', FunctionTransformer(
     remove_underscore
 )),
 ('remove_number', FunctionTransformer(
     remove_number
 )),
 ('remove_non_alphabetic_char', FunctionTransformer(
     remove_non_alphabetic
 )),
 ('remove_kata_ulang', FunctionTransformer(
     remove_kata_ulang
 )),
 ('remove_laughing', FunctionTransformer(
     remove_laughing
 )),
 ('tf_idf', TfidfVectorizer(
     stop_words=stop_words
 )),
 ('sampler', RandomOverSampler(
     sampling_strategy='not majority',
     random_state=RANDOM_STATE
 )),
 ('algo', MultinomialNB())
])

# random under sampling
NB_imb_RUS = Pipeline([
 ('normalize_unicode', FunctionTransformer(
     normalize_unicode
 )),
 ('remove_generated_mess', FunctionTransformer(
     remove_feature_generated_mess
 )),
 ('remove_underscore', FunctionTransformer(
     remove_underscore
 )),
 ('remove_number', FunctionTransformer(
     remove_number
 )),
 ('remove_non_alphabetic_char', FunctionTransformer(
     remove_non_alphabetic
 )),
 ('remove_kata_ulang', FunctionTransformer(
     remove_kata_ulang
 )),
 ('remove_laughing', FunctionTransformer(
     remove_laughing
 )),
 ('tf_idf', TfidfVectorizer(
     stop_words=stop_words
 )),
 ('sampler', RandomUnderSampler(
     sampling_strategy='not minority',
     random_state=RANDOM_STATE
 )),
 ('algo', MultinomialNB())
])

## Cross Validation to get best parameter

In [41]:
from sklearn.model_selection import GridSearchCV

In [42]:
from multiprocessing import cpu_count
n_cpus = cpu_count() # 8
n_cpus # 8

8

In [43]:
# I decide to use 4 n_jobs here, the value heavily depends on your own pc's specs
n_jobs = 4

In [44]:
from datetime import datetime as dt
from datetime import timezone

pipes = [
    NB,
    NB_imb_RUS,
    NB_imb_ROS
]
for pipe in pipes:
    start = dt.now(timezone.utc)
    NB_parameters = {
        'tf_idf__use_idf': [True, False],
        'tf_idf__ngram_range': [(1, 1), (1, 2), (1,3)],
        'algo__alpha': [0.00001, 0.0001, 0.001, 0.1, 1, 10, 100,1000],
        'algo__fit_prior': [True, False]
    }
    
    NB_search = GridSearchCV(
        pipe, param_grid=NB_parameters,
        cv=4, verbose=1, scoring='f1_macro',
        n_jobs=n_jobs
    )
    
    NB_search.fit(X_train, y_train)
    fit_seconds = (dt.now(timezone.utc) - start).total_seconds()
    
    pipe_steps_dict = {name: type(step).__name__ for name, step in NB_search.best_estimator_.steps}

    experiment = {
        "meta": {
            "algorithm": pipe_steps_dict['algo'],
            "sampler": pipe_steps_dict.get('sampler'),
            "scoring": NB_search.scoring,
            "random_state": RANDOM_STATE,
            "fit_seconds": fit_seconds,
            "created_at": dt.now(timezone.utc).isoformat()
        },
        'search_result': NB_search,
    }

    import pickle
    
    file_name = "_".join(str(x) for x in [
        start.strftime("%Y%m%d_%H%M%S"),
        pipe_steps_dict['algo'],
        pipe_steps_dict.get('sampler'),
        NB_search.scoring
    ] if x is not None)
    
    os.makedirs("./pickled_models", exist_ok=True)
    pickle.dump(experiment, open(f"./pickled_models/{file_name}.pkl", 'wb'))
    
    print(NB_search.score(X_train, y_train), NB_search.best_score_, NB_search.score(X_test, y_test))

Fitting 4 folds for each of 96 candidates, totalling 384 fits
0.9853650408796968 0.5855506056861788 0.5793623688379499
Fitting 4 folds for each of 96 candidates, totalling 384 fits
0.7161565366737307 0.5769877367102667 0.5743308585422939
Fitting 4 folds for each of 96 candidates, totalling 384 fits
0.8651494924184261 0.6079579705404904 0.6067211559345763

In [45]:
# !pip install Sastrawi
# !pip install matplotlib
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, FunctionTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
import nltk
nltk.download('stopwords')
from nltk.tokenize import word_tokenize
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from nltk.corpus import stopwords
from sklearn.naive_bayes import MultinomialNB
from imblearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import pickle
RANDOM_STATE = 11

/home/nwxxb/Documents/sampling_differences_experiment/.venv/lib/python3.10/site-packages/nltk/downloader.py:1076: UserWarning: NLTK will not authorize the non-private download directory '/home/nwxxb/nltk_data': it (or an ancestor) is world- or group-writable, so another local user could plant files there. Choose a private location such as ~/nltk_data.
  for msg in self.incr_download(info_or_id, download_dir, force):
[nltk_data] Downloading package stopwords to /home/nwxxb/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [46]:
import gdown
gdown.download(url='https://drive.google.com/file/d/196RvhKcO_iwX7RzGiM7fxlpCUR9v7beB/view?usp=drive_link', output='test_model.pkl', quiet=False, fuzzy=True)

TypeError: download() got an unexpected keyword argument 'fuzzy'

In [ ]:
def normalize_unicode(X):
  # try to remove 𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺, ˢᵉᵐᵘᵃ, 𝐊𝐢𝐭𝐚, etc..
  X = X.copy()
  X = X.str.normalize('NFKC')
  return X

def remove_number(X):
  X = X.copy()
  X = X.str.replace(r"\d+", '')
  return X

def remove_feature_generated_mess(X):
  X = X.copy()
  X = X.str.replace(r"\[\[\^[(face|space)\-]{0,6}[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}\]\]", '')
  return X

def remove_underscore(X):
  X = X.copy()
  X = X.str.replace(r"_", ' ')
  return X

def remove_non_alphabetic(X):
  regex = r"[\u0600-\u06ff]|[\ua980-\ua9df]|[\u1b80-\u1bbf]|[\u1cc0-\u1ccf]|[\u1b00-\u1b7f]|[\u1bc0-\u1bff]|[\u4e00-\u9fff]|[\u0590-\u05ff]|[\ufb1d-\ufb4f]"
  X = X.copy()
  X = X.str.replace(regex, '')
  return X

def remove_kata_ulang(X):
  X = X.copy()
  X = X.str.replace(r"([a-z])(2)", r'\1', regex=True)
  return X

def remove_laughing(X): #TODO
  X = X.copy()
  X = X.str.replace(r"\b(?:[akiq]{0,2}[hwx]{1,2}[akiq]{0,2}){2,}h?\b", '', regex=True)
  return X

def stem_indo(X):
  return X

def test_print(X, payload):
  print(payload)
  return X

In [ ]:
pickle_obj1 = pickle.load(open('test_model.pkl', 'rb'))

models = pickle_obj1['grid_search_obj']
print(pickle_obj1['notes'])
X_train, X_test, y_train, y_test = [
    pickle_obj1['train_data']['X_train'],
    pickle_obj1['test_data']['X_test'],
    pickle_obj1['train_data']['y_train'],
    pickle_obj1['test_data']['y_test'],
]
print(pickle_obj1['train_data']['y_train'].shape)
print(pickle_obj1['test_data']['y_test'].shape)

In [ ]:
pickle_obj1 = pickle.load(open('model_1_naive_bayes_f1_macro_rs11(fix).pkl', 'rb'))
pickle_obj2 = pickle.load(open('model_2_naive_bayes_f1_macro_rs11.pkl', 'rb'))
pickle_obj3 = pickle.load(open('model_3_naive_bayes_f1_macro_rs11.pkl', 'rb'))
models = [pickle_obj1['grid_search_obj'], pickle_obj2['grid_search_obj'], pickle_obj3['grid_search_obj']]
print(pickle_obj1['notes'])
print(pickle_obj2['notes'])
print(pickle_obj3['notes'])
X_train, X_test, y_train, y_test = [
    pickle_obj1['train_data']['X_train'],
    pickle_obj1['test_data']['X_test'],
    pickle_obj1['train_data']['y_train'],
    pickle_obj1['test_data']['y_test'],
]
print(pickle_obj1['train_data']['y_train'].shape)
print(pickle_obj2['train_data']['y_train'].shape)
print(pickle_obj3['train_data']['y_train'].shape)
print(pickle_obj1['test_data']['y_test'].shape)
print(pickle_obj2['test_data']['y_test'].shape)
print(pickle_obj3['test_data']['y_test'].shape)

In [ ]:
for model in models:
  print(model.best_score_)

In [ ]:
for model in models:
  print(model.best_params_)

In [ ]:
temp_arr = []
for model in models:
  temp_arr.append(model.score(X_train, y_train))

print(temp_arr)

In [ ]:
type(y_test)

In [ ]:
from sklearn.metrics import roc_auc_score, balanced_accuracy_score, f1_score, accuracy_score
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import precision_score, recall_score, roc_auc_score, mean_squared_error

balanced_accuracies = []
roc_auc_scores = []
precisions = []
recalls = []
f1 = []
y_pred_counts_arr = []

for model in models:
  y_pred = model.predict(X_test)
  y_pred_prob = model.predict_proba(X_test)
  y_pred_counts_arr.append(pd.Series(y_pred).value_counts())
  balanced_accuracies.append(balanced_accuracy_score(y_test, y_pred))
  f1.append(f1_score(y_test, y_pred, average='macro'))
  precisions.append(precision_score(y_test, y_pred, average='macro'))
  recalls.append(recall_score(y_test, y_pred, average='macro'))
  roc_auc_scores.append(roc_auc_score(y_test, y_pred_prob, multi_class='ovr'))

In [ ]:
print('model 1')
print(balanced_accuracies[0])
print(roc_auc_scores[0])
print(precisions[0])
print(recalls[0])
print(f1[0])
print('model 2')
print(balanced_accuracies[1])
print(roc_auc_scores[1])
print(precisions[1])
print(recalls[1])
print(f1[1])
print('model 3')
print(balanced_accuracies[2])
print(roc_auc_scores[2])
print(precisions[2])
print(recalls[2])
print(f1[2])

In [ ]:
model_label = ['model1', 'model2', 'model3']
fig, ax = plt.subplots()
ax.plot(model_label, precisions, label="precision (macro)")
ax.plot(model_label, recalls, label="recalls (macro)")
ax.plot(model_label, f1, label="f1_score (macro)")
ax.legend()
plt.title("precisions, recalls, and f1 scores")

plt.show()

In [ ]:
print(roc_auc_scores)

In [ ]:
model_label = ['model1', 'model2', 'model3']
fig, ax = plt.subplots()
ax.plot(model_label, roc_auc_scores)
ax.legend()
plt.title("ROC AUC scores")

plt.show()

In [ ]:
model_label = ['model1', 'model2', 'model3']
fig, ax = plt.subplots()
ax.plot(model_label, balanced_accuracies)
ax.legend()
plt.title("balanced accuracies")

plt.show()

In [ ]:
f1_scores = {}
precisions_dict = {}
recalls_dict = {}
for label, model in zip(model_label, models):
  y_pred = model.predict(X_test)
  f1_scores[label] = f1_score(y_test, y_pred, average=None)
  precisions_dict[label] = precision_score(y_test, y_pred, average=None)
  recalls_dict[label] = recall_score(y_test, y_pred, average=None)

In [ ]:
y_train.value_counts()

In [ ]:
class_labels = [6.0, 7.0, 10.0, 11.0, 13.0, 14.0, 15.0, 21.0, 22.0, 31.0, 43.0, 51.0]
name_labels = ["Sains", "Pertanian", "Ekonomi Bisnis", "Filsafat", "Sosial Budaya", "Politik", "Psikologi", "Agama", "Pendidikan", "Sejarah", "Islam", "Kesehatan"]

In [ ]:
precision_df = pd.DataFrame(precisions_dict, index=class_labels)
precision_df = precision_df.join(y_train.value_counts())
precision_df = precision_df.join(topics)
precision_df.rename(columns={'topic_id': 'qty'}, inplace=True)

recall_df = pd.DataFrame(recalls_dict, index=class_labels)
recall_df = recall_df.join(y_train.value_counts())
recall_df = recall_df.join(topics)
recall_df.rename(columns={'topic_id': 'qty'}, inplace=True)

precision_df = precision_df.sort_values(by=['qty'])
recall_df = recall_df.sort_values(by=['qty'])

In [ ]:
display(precision_df)
display(recall_df)

In [ ]:
# ax = precision_df[['model1', 'model2', 'model3', 'topic_name']].plot(x="topic_name", kind='bar', figsize=(10, 10), title="precision on each class")
# precision_df[['precision_mean', 'topic_name']].plot(x="topic_name", kind='line', ax=ax)
precision_df[['model1', 'model2', 'model3', 'topic_name']].plot(x="topic_name", kind='bar', figsize=(10, 10), title="precision on each class")
recall_df[['model1', 'model2', 'model3', 'topic_name']].plot(x="topic_name", kind='bar', figsize=(10, 10), title="recall on each class")

In [ ]:
plot_df = pd.DataFrame(f1_scores, index=class_labels)
plot_df = plot_df.join(y_train.value_counts())
plot_df = plot_df.join(topics)
plot_df.rename(columns={'topic_id': 'qty'}, inplace=True)

In [ ]:
plot_df

In [ ]:
sorted_plot_df = plot_df.sort_values(by=['qty'])
sorted_plot_df

In [ ]:
# plot grouped bar chart
sorted_plot_df[['model1', 'model2', 'model3', 'topic_name']].plot(x="topic_name", kind='bar', figsize=(10, 10), title="f1_score on each class")

In [ ]:
y_pred_dict = {
    'model1': y_pred_counts_arr[0],
    'model2': y_pred_counts_arr[1],
    'model3': y_pred_counts_arr[2],
}
y_pred_df = pd.DataFrame(y_pred_dict, index=class_labels)
y_pred_df = y_pred_df.join(y_test.value_counts())
y_pred_df = y_pred_df.join(y_train.value_counts(), lsuffix='_test')
y_pred_df = y_pred_df.join(topics)
y_pred_df.rename(columns={'topic_id': 'qty', 'topic_id_test': 'actual_label'}, inplace=True)
display(y_pred_df)

In [ ]:
sorted_y_pred_df = y_pred_df.sort_values(by=['qty'])
display(sorted_y_pred_df)

In [ ]:
sorted_y_pred_df[['model1', 'model2', 'model3', 'actual_label', 'topic_name']].plot(x="topic_name", kind='bar', figsize=(10, 10), title="predicted label on each class")

In [ ]:
pickle_obj_only_post = pickle.load(open('model_3_only_post_naive_bayes_f1_macro_rs11.pkl', 'rb'))
pickle_obj = pickle.load(open('model_3_naive_bayes_f1_macro_rs11.pkl', 'rb'))

models = pickle_obj['grid_search_obj']
print(pickle_obj['notes'])
X_train, X_test, y_train, y_test = [
    pickle_obj['train_data']['X_train'],
    pickle_obj['test_data']['X_test'],
    pickle_obj['train_data']['y_train'],
    pickle_obj['test_data']['y_test'],
]
print(pickle_obj['train_data']['y_train'].shape)
print(pickle_obj['test_data']['y_test'].shape)

In [ ]:
only_post_df = pd.DataFrame(pickle_obj_only_post['train_data']['y_train'].value_counts())
post_comment_df = pd.DataFrame(pickle_obj['train_data']['y_train'].value_counts())
only_post_df = only_post_df.join(topics)
post_comment_df = post_comment_df.join(topics)
only_post_df.rename(columns={'topic_id': 'quantity'}, inplace=True)
post_comment_df.rename(columns={'topic_id': 'quantity'}, inplace=True)
only_post_df.sort_values(by=['quantity'], inplace=True)
post_comment_df.sort_values(by=['quantity'], inplace=True)
display(only_post_df)
display(post_comment_df)

In [ ]:
only_post_df[['quantity', 'topic_name']].plot(x="topic_name", kind='bar', figsize=(10, 10), title="only post: data train quantity")
post_comment_df[['quantity', 'topic_name']].plot(x="topic_name", kind='bar', figsize=(10, 10), title="post & comment: data train quantity")

In [ ]:
pre_test = Pipeline([
    # ('test1', FunctionTransformer(test_print, kw_args={'payload': 'preprocessing start'})), #
    ('normalize_unicode', FunctionTransformer(normalize_unicode)),
    ('remove_generated_mess', FunctionTransformer(remove_feature_generated_mess)),
    ('remove_underscore', FunctionTransformer(remove_underscore)),
    ('remove_number', FunctionTransformer(remove_number)),
    # ('test2', FunctionTransformer(test_print, kw_args={'payload': 'remove_generated_mess selesai'})), #
    ('remove_non_alphabetic_char', FunctionTransformer(remove_non_alphabetic)),
    # ('test3', FunctionTransformer(test_print, kw_args={'payload': 'remove_non_alphabetic_char selesai'})), #
    ('remove_kata_ulang', FunctionTransformer(remove_kata_ulang)),
    # ('test4', FunctionTransformer(test_print, kw_args={'payload': 'remove_kata_ulang selesai'})), #
    # ('test5', FunctionTransformer(test_print, kw_args={'payload': 'preprocessing (pre tf-idf) sudah selesai'})), #
    ('remove_laughing', FunctionTransformer(remove_laughing)),
    ('tf_idf', TfidfVectorizer(stop_words=stop_words)),
     # tackle imbalance class: only resample training data
    # ('nb_algo', MultinomialNB())
])

resampler = Pipeline([
    ('under_sampler', RandomUnderSampler(sampling_strategy='not minority',random_state=RANDOM_STATE)),
    # ('over_sampler', RandomOverSampler(sampling_strategy='not majority', random_state=RANDOM_STATE))
])

In [ ]:
X_result = pre_test.fit_transform(pickle_obj['train_data']['X_train'])
X_pre, y_pre = resampler.fit_resample(X_result, pickle_obj['train_data']['y_train'])

In [ ]:
y_pre.value_counts(), pickle_obj['train_data']['y_train'].value_counts()

In [ ]:
temp_df = pd.DataFrame(y_pre.value_counts())
temp_df = temp_df.join(pickle_obj['train_data']['y_train'].value_counts(), lsuffix='_blip')
temp_df = temp_df.join(topics)
temp_df.rename(columns={'topic_id_blip': 'quantity_after', 'topic_id': 'quantity_before'}, inplace=True)
temp_df.sort_values(by=['quantity_before'], inplace=True)
display(temp_df)

In [ ]:
temp_df[['quantity_before', 'quantity_after', 'topic_name']].plot(x="topic_name", kind='bar', figsize=(10, 10), title="post & comment: data train quantity")

In [ ]:
print(classification_report(y_test, y_pred))

In [ ]:
f1 = f1_score(y_test, y_pred, average=None)
for val in f1:
  print(val)

In [ ]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average=None)
for val in precision:
  print(val)

In [ ]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred, average=None)
for val in recall:
  print(val)

In [ ]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
disp = ConfusionMatrixDisplay.from_predictions(
                  y_test,
                  y_pred,
                  cmap=plt.cm.Blues,
)
fig = disp.ax_.get_figure()
fig.set_figwidth(10)
fig.set_figheight(10)

In [ ]:
coba_text = [
    "islam adalah agama rahmatan lil-alamin, dan sharusnya konsep ini sepertinya ada di semua agama lain",
    "Kalian kalau belajar kimia atau fisika bagaimana?",
    "Saya kadang ada masalah sama keluarga saya, bagaimana ya cara mengatasinya",
    "Para pemerintah itu kok bangsat semua sih",
    "kawan-kawan, tolong rekomendasikan saya buku yang mantep untuk belajar sejarah dan sosbud Islam di jawa",
    "cara pakai symbolic ini gimana sih?",
    "cara buka ternak lele gimana ya? dan apa saja resikonya?",
    "Saya sering begadang, merokok, dan minum kopi. apa saja ya resiko kedepannya?"
]

In [ ]:
model.predict_proba(pd.Series(data=coba_text))[0]

In [ ]:
model.predict(pd.Series(data=coba_text))[0]

In [ ]:
# print best parameter after tuning
print(model.best_params_)
grid_predictions = model.predict(X_test)
# print classification report
print(classification_report(y_test, grid_predictions))

#### get resampled data

In [ ]:
pre_test = Pipeline([
    # ('test1', FunctionTransformer(test_print, kw_args={'payload': 'preprocessing start'})), #
    ('normalize_unicode', FunctionTransformer(normalize_unicode)),
    ('remove_generated_mess', FunctionTransformer(remove_feature_generated_mess)),
    ('remove_underscore', FunctionTransformer(remove_underscore)),
    ('remove_number', FunctionTransformer(remove_number)),
    # ('test2', FunctionTransformer(test_print, kw_args={'payload': 'remove_generated_mess selesai'})), #
    ('remove_non_alphabetic_char', FunctionTransformer(remove_non_alphabetic)),
    # ('test3', FunctionTransformer(test_print, kw_args={'payload': 'remove_non_alphabetic_char selesai'})), #
    ('remove_kata_ulang', FunctionTransformer(remove_kata_ulang)),
    # ('test4', FunctionTransformer(test_print, kw_args={'payload': 'remove_kata_ulang selesai'})), #
    # ('test5', FunctionTransformer(test_print, kw_args={'payload': 'preprocessing (pre tf-idf) sudah selesai'})), #
    ('remove_laughing', FunctionTransformer(remove_laughing)),
    ('tf_idf', TfidfVectorizer(stop_words=stop_words)),
     # tackle imbalance class: only resample training data
    # ('nb_algo', MultinomialNB())
])

resampler = Pipeline([
    ('under_sampler', RandomUnderSampler(sampling_strategy='not minority',random_state=RANDOM_STATE)),
    ('over_ampler', RandomOverSampler(sampling_strategy='not majority', random_state=RANDOM_STATE))
])

In [ ]:
X_result = pre_test.fit_transform(X_train)
X_pre, y_pre = model.estimator['sampler'].fit_resample(X_result, y_train)

In [ ]:
X_train.shape, y_train.shape

In [ ]:
X_pre.shape, y_pre.shape

In [ ]:
print(X_pre)

In [ ]:
wm = X_pre.todense()

In [ ]:
wm.shape

In [ ]:
type(wm)

In [ ]:
wm[0]

In [ ]:
y_pre.head(5)

In [ ]:
X_pre.toarray()

In [ ]:
y_pre.filter(like='15.0', axis=0)

In [ ]:
import matplotlib.pyplot as plt
label_dict = {
	51.0: "Kesehatan",
	11.0: "Filsafat",
	15.0: "Psikologi",
	21.0: "Agama",
	6.0: "Sains",
	43.0: "Islam",
	10.0: "Ekonomi Bisnis",
	14.0: "Politik",
	22.0: "Pendidikan",
	13.0: "Sosial Budaya",
	31.0: "Sejarah",
	7.0: "Pertanian"
}


ser = y_pre.value_counts()
ser.rename(label_dict)
ser.plot.bar()
plt.title('data train size (without resample)')

In [ ]:
model.best_params_

In [ ]:
preprocessor_test = Pipeline([
    ('test1', FunctionTransformer(test_print, kw_args={'payload': 'preprocessing start'})),
    ('normalize_unicode', FunctionTransformer(normalize_unicode)),
    ('remove_generated_mess', FunctionTransformer(remove_feature_generated_mess)),
    ('remove_underscore', FunctionTransformer(remove_underscore)),
    ('remove_number', FunctionTransformer(remove_number)),
    ('remove_non_alphabetic_char', FunctionTransformer(remove_non_alphabetic)),
    ('remove_kata_ulang', FunctionTransformer(remove_kata_ulang)),
    ('remove_laughing', FunctionTransformer(remove_laughing)),
    ('tf_idf', TfidfVectorizer(stop_words=stop_words, ngram_range=(1, 1), use_idf=False))
])

In [ ]:
tf_idf_result = preprocessor_test.fit_transform(X_train, y_train)

In [ ]:
preprocessor_test['tf_idf']

In [ ]:
NB_imb_ROS_test = Pipeline([
    # ('test1', FunctionTransformer(test_print, kw_args={'payload': 'preprocessing start'})), #
    ('normalize_unicode', FunctionTransformer(normalize_unicode)),
    ('remove_generated_mess', FunctionTransformer(remove_feature_generated_mess)),
    ('remove_underscore', FunctionTransformer(remove_underscore)),
    ('remove_number', FunctionTransformer(remove_number)),
    # ('test2', FunctionTransformer(test_print, kw_args={'payload': 'remove_generated_mess selesai'})), #
    ('remove_non_alphabetic_char', FunctionTransformer(remove_non_alphabetic)),
    # ('test3', FunctionTransformer(test_print, kw_args={'payload': 'remove_non_alphabetic_char selesai'})), #
    ('remove_kata_ulang', FunctionTransformer(remove_kata_ulang)),
    # ('test4', FunctionTransformer(test_print, kw_args={'payload': 'remove_kata_ulang selesai'})), #
    # ('test5', FunctionTransformer(test_print, kw_args={'payload': 'preprocessing (pre tf-idf) sudah selesai'})), #
    ('tf_idf', TfidfVectorizer(stop_words=stop_words)),
    ('sampler', RandomOverSampler('minority', random_state=RANDOM_STATE)), # tackle imbalance class: only resample training data
])

In [ ]:
X_result.shape, y_train.shape

In [ ]:
X_result.shape

In [ ]:
X_hihi, y_hihi = RandomOverSampler(sampling_strategy='minority', random_state=RANDOM_STATE).fit_resample(X_result, y_train)

In [ ]:
X_hihi.shape, y_hihi.shape, y_train.shape

In [ ]:
y_train.head(5)

In [ ]:
y_hihi.head(5)

In [ ]:
y_hihi.value_counts()

In [ ]:
ser = y_hihi.value_counts()
ser.rename(label_dict)
ser.plot.bar()
plt.title('data train size (Random Over Sampling)')

In [ ]:
X_hihi.size, y_hihi

In [ ]:
X = model.estimator['pre'].fit_transform(X_train, y_train)

In [ ]:
y_train.value_counts()

In [ ]:
# !pip install scikit-learn==1.0.2 # I don't know why we need this, I think there is some weird ness on pickled model

In [ ]:
# !pip install Sastrawi
# !pip install matplotlib
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, FunctionTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
import nltk
nltk.download('stopwords')
from nltk.tokenize import word_tokenize
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from nltk.corpus import stopwords
from sklearn.naive_bayes import MultinomialNB
from imblearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import pickle
RANDOM_STATE = 11

In [ ]:
def normalize_unicode(X):
  # try to remove 𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺, ˢᵉᵐᵘᵃ, 𝐊𝐢𝐭𝐚, etc..
  X = X.copy()
  X = X.str.normalize('NFKC')
  return X

def remove_number(X):
  X = X.copy()
  X = X.str.replace(r"\d+", '')
  return X

def remove_feature_generated_mess(X):
  X = X.copy()
  X = X.str.replace(r"\[\[\^[(face|space)\-]{0,6}[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}\]\]", '')
  return X

def remove_underscore(X):
  X = X.copy()
  X = X.str.replace(r"_", ' ')
  return X

def remove_non_alphabetic(X):
  regex = r"[\u0600-\u06ff]|[\ua980-\ua9df]|[\u1b80-\u1bbf]|[\u1cc0-\u1ccf]|[\u1b00-\u1b7f]|[\u1bc0-\u1bff]|[\u4e00-\u9fff]|[\u0590-\u05ff]|[\ufb1d-\ufb4f]"
  X = X.copy()
  X = X.str.replace(regex, '')
  return X

def remove_kata_ulang(X):
  X = X.copy()
  X = X.str.replace(r"([a-z])(2)", r'\1', regex=True)
  return X

def remove_laughing(X): #TODO
  X = X.copy()
  X = X.str.replace(r"\b(?:[akiq]{0,2}[hwx]{1,2}[akiq]{0,2}){2,}h?\b", '', regex=True)
  return X

def stem_indo(X):
  return X

def test_print(X, payload):
  print(payload)
  return X

In [ ]:
pickled_obj = []
# for i in range(1, 4):
  # pickled_obj.append(pickle.load(open(f'model_{i}_only_post_naive_bayes_f1_macro_rs11.pkl', 'rb')))

# 23 Oct 2023: I only have this one model
pickled_obj.append(pickle.load(open(f'model_2_only_post_naive_bayes_f1_macro_rs11.pkl', 'rb')))

for obj in pickled_obj:
  print(obj['notes'])
  print(obj['train_data']['y_train'].shape)
  print(obj['test_data']['y_test'].shape)
  print()

X_train, X_test, y_train, y_test = [
    pickled_obj[0]['train_data']['X_train'],
    pickled_obj[0]['test_data']['X_test'],
    pickled_obj[0]['train_data']['y_train'],
    pickled_obj[0]['test_data']['y_test'],
]